### ISSUE TITLE
Add Solana and AVAX, BSC & Polygon Testnets to Portal UI

### ISSUE THREAD

**Issue by moatus** [pokt-foundation/pocketUI#13]
Avalanche Fuji 000E

Binance Smart Chain Testnet 0011

Binance Smart Chain Testnet Archival 0012

Polygon Mumbai 000F

Polygon Mumbai Archival 00AF

Solana 0006

**Comment by Evalir** [comment]
Moving to https://github.com/pokt-foundation/portal/issues/282
