### ISSUE TITLE
Add Algorand to portal on Friday 9/24

### ISSUE THREAD

**Issue by RichardJamesLopez** [pokt-foundation/pocketUI#16]
Please add 

- Algorand Mainnet (0029) and 
- Algorand Archival (000D) 

to the Portal for users to mint endpoints after on Friday 9/24 confirming that Settler is properly set up.

**Comment by Evalir** [comment]
Hey @RichardJamesLopez , could we move this over to https://github.com/pokt-foundation/portal ? This is the repo for the design system implementation. Will close this!
