### ISSUE TITLE
add Harmony Mainnet Shard 0 endpoint to Portal  

### ISSUE THREAD

**Issue by RichardJamesLopez** [pokt-foundation/pocketUI#19]
Can we add Harmony Mainnet Shard 0 endpoint to Portal after noon EST on 10/6/2021.    

We are whitelisting Harmony Shard 0 (0040)  at ! 11am EST on the same day.

Note: we will not be adding Archival on the same day. We will whitelist (and add) that later on.

**Comment by Evalir** [comment]
Moving to https://github.com/pokt-foundation/portal/issues/281
